version: '3.8'

services:
  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  api:
    build: .
    ports:
      - "8003:8003"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - AUTH_TOKEN=your_secure_token_here
      - WORKFLOWS_DIR=/app/workflows
      - MINIO_ENDPOINT=192.168.1.115:9000
      - MINIO_ACCESS_KEY=chuzeyu
      - MINIO_SECRET_KEY=@Cv1347968277
      - MINIO_BUCKET=bot-data
      - MINIO_INPUT_BUCKET=comfyui-input
      - MINIO_RESULT_BUCKET=comfyui-temp
      - MINIO_TEMPLATE_BUCKET=bot-template
      - MINIO_SECURE=false
      - AGENT_SECRET_TOKEN=super_secret_agent_token_2026
    volumes:
      - ./workflows:/app/workflows
      - ./app:/app/app
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

volumes:
  redis_data:
